1: friends.c
	gcc $< -o $@
2: funds1.c
	gcc $< -o $@
3: funds2.c
	gcc $< -o $@
4: funds3.c
	gcc $< -o $@
5: funds4.c
	gcc $< -o $@
6: names1.c
	gcc $< -o $@
7: names2.c
	gcc $< -o $@
8: names3.c
	gcc $< -o $@
9: films1.c
	gcc $< -o $@
10: films2.c
	gcc $< -o $@ 
clean: 
	rm ?
