#This Makefile is used to generate the executables of the class 20

1: zippo1.c
	gcc $< -o $@ -g
2: zippo2.c
	gcc $< -o $@ -g
3: pointer_2darray.c
	gcc $< -o $@ -g
4: array2d.c
	gcc $< -o $@ -g
5: dyn_arr.c
	gcc $< -o $@ -g
6: reallocating.c
	gcc $< -o $@ -g
clean:
	rm ?


